[package]
name = "gloam"
version = "0.1.0"
edition = "2021"

[dependencies]
derivative = "2.2.0"
gl = "0.14.0"
glfw = "0.58.0"
image = "0.25.4"
log = "0.4.22"
nalgebra-glm = "0.19.0"
thiserror = "1.0.64"
env_logger = "0.11.5"
